# Generated by Django 6.0.3 on 2026-04-08 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0002_formquestion_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('validated', 'Validated'), ('accepted', 'Accepted'), ('suspicious', 'Suspicious'), ('rejected', 'Rejected'), ('queued_for_analysis', 'Queued for analysis'), ('analyzed', 'Analyzed'), ('analysis_failed', 'Analysis failed'), ('analysis_skipped_limit', 'Analysis skipped limit')], default='received', max_length=32)),
                ('analysis_eligible', models.BooleanField(default=False)),
                ('dashboard_eligible', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('suspicious_at', models.DateTimeField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.feedbackform')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating_value', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms.formquestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='submissions.feedbacksubmission')),
            ],
        ),
        migrations.AddIndex(
            model_name='feedbacksubmission',
            index=models.Index(fields=['organization'], name='submissions_organiz_0643f3_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacksubmission',
            index=models.Index(fields=['form'], name='submissions_form_id_30b530_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacksubmission',
            index=models.Index(fields=['status'], name='submissions_status_5cad0e_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacksubmission',
            index=models.Index(fields=['submitted_at'], name='submissions_submitt_0453ef_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacksubmission',
            index=models.Index(fields=['organization', 'submitted_at'], name='submissions_organiz_b3c51d_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacksubmission',
            index=models.Index(fields=['organization', 'status', 'submitted_at'], name='submissions_organiz_f67dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacksubmission',
            index=models.Index(fields=['form', 'submitted_at'], name='submissions_form_id_3e3b68_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionanswer',
            index=models.Index(fields=['submission'], name='submissions_submiss_2ffb7e_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionanswer',
            index=models.Index(fields=['question'], name='submissions_questio_40c8d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='submissionanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='unique_answer_per_question_in_submission'),
        ),
    ]
