# Generated by Django 6.0.3 on 2026-04-22 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_score', models.PositiveSmallIntegerField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('decision', models.CharField(choices=[('accepted', 'Accepted'), ('suspicious', 'Suspicious'), ('rejected', 'Rejected')], max_length=20)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('engine_version', models.CharField(default='v1', max_length=50)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='submissions.feedbacksubmission')),
            ],
            options={
                'indexes': [models.Index(fields=['decision'], name='submissions_decisio_7a26c3_idx'), models.Index(fields=['risk_level'], name='submissions_risk_le_97af7e_idx'), models.Index(fields=['evaluated_at'], name='submissions_evaluat_fba75a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('risk_score__gte', 0), ('risk_score__lte', 100)), name='submission_risk_score_between_0_and_100')],
            },
        ),
        migrations.CreateModel(
            name='SubmissionTechnicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('fingerprint_hash', models.CharField(blank=True, max_length=255)),
                ('accept_language', models.CharField(blank=True, max_length=255)),
                ('referer', models.URLField(blank=True)),
                ('captcha_provider', models.CharField(blank=True, max_length=100)),
                ('captcha_passed', models.BooleanField(default=False)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_data', to='submissions.feedbacksubmission')),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address'], name='submissions_ip_addr_aa69bb_idx'), models.Index(fields=['fingerprint_hash'], name='submissions_fingerp_734b4d_idx'), models.Index(fields=['ip_address', 'created_at'], name='submissions_ip_addr_52e874_idx'), models.Index(fields=['fingerprint_hash', 'created_at'], name='submissions_fingerp_e516f4_idx')],
            },
        ),
    ]
