# Generated by Django 6.0.3 on 2026-04-22 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0002_submissionriskassessment_submissiontechnicaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sentiment', models.CharField(max_length=20)),
                ('urgency', models.CharField(max_length=20)),
                ('topics', models.JSONField(default=list)),
                ('summary', models.TextField()),
                ('raw_response', models.JSONField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='submissions.feedbacksubmission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_job', to='submissions.feedbacksubmission')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='analysis_an_status_69ee01_idx'), models.Index(fields=['scheduled_at'], name='analysis_an_schedul_1e2229_idx')],
            },
        ),
    ]
