# Generated by Django 6.0.3 on 2026-04-22 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('plans', '0001_initial'),
        ('submissions', '0002_submissionriskassessment_submissiontechnicaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('analysis_used', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_buckets', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization'], name='plans_usage_organiz_3874d2_idx'), models.Index(fields=['period_start', 'period_end'], name='plans_usage_period__bb1b07_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('analysis', 'Analysis')], max_length=20)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='organizations.organization')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='submissions.feedbacksubmission')),
            ],
            options={
                'indexes': [models.Index(fields=['organization'], name='plans_usage_organiz_c3364f_idx'), models.Index(fields=['event_type'], name='plans_usage_event_t_471980_idx')],
            },
        ),
    ]
