# Generated by Django 6.0.3 on 2026-04-01 21:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('allow_text', models.BooleanField(default=True)),
                ('is_text_required', models.BooleanField(default=False)),
                ('min_score', models.PositiveSmallIntegerField(default=1)),
                ('max_score', models.PositiveSmallIntegerField(default=5)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization'], name='forms_feedb_organiz_6a9c62_idx'), models.Index(fields=['status'], name='forms_feedb_status_e2df48_idx'), models.Index(fields=['organization', 'status'], name='forms_feedb_organiz_f491a2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('min_score__lte', models.F('max_score'))), name='feedback_form_min_score_lte_max_score')],
            },
        ),
    ]
