# Generated by Django 6.0.3 on 2026-04-08 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('rating', 'Rating'), ('text', 'Text')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField()),
                ('min_value', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_value', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='feedbackform',
            name='feedback_form_min_score_lte_max_score',
        ),
        migrations.AddField(
            model_name='formquestion',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms.feedbackform'),
        ),
        migrations.RemoveField(
            model_name='feedbackform',
            name='allow_text',
        ),
        migrations.RemoveField(
            model_name='feedbackform',
            name='is_text_required',
        ),
        migrations.RemoveField(
            model_name='feedbackform',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='feedbackform',
            name='min_score',
        ),
        migrations.AddIndex(
            model_name='formquestion',
            index=models.Index(fields=['form'], name='forms_formq_form_id_36d264_idx'),
        ),
        migrations.AddIndex(
            model_name='formquestion',
            index=models.Index(fields=['form', 'order'], name='forms_formq_form_id_036f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='formquestion',
            index=models.Index(fields=['question_type'], name='forms_formq_questio_ce8959_idx'),
        ),
        migrations.AddConstraint(
            model_name='formquestion',
            constraint=models.UniqueConstraint(fields=('form', 'order'), name='unique_question_order_per_form'),
        ),
    ]
