# Generated by Django 6.0.3 on 2026-05-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='require_captcha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='security_level',
            field=models.CharField(choices=[('relaxed', 'Relaxed'), ('standard', 'Standard'), ('strict', 'Strict')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='suspicious_submission_policy',
            field=models.CharField(choices=[('flag', 'Flag'), ('accept', 'Accept'), ('reject', 'Reject')], default='flag', max_length=20),
        ),
    ]
